development:
  adapter: mysql2
  encoding: utf8
  database: deliveries_development
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: deliveries_prod
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
